import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'CitizenSync',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="fr" className="">
            <body className={`bg-stone-900 text-white grid grid-cols-1 grid-rows-[min-content_auto]`}>{children}</body>
        </html>
    )
}
